version: '3.8'
services:
  telescope:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - "8888:8888"
    volumes:
      - ./accounts:/app/accounts